/* Compilador.java */
/* Generated By:JavaCC: Do not edit this line. Compilador.java */
  import java.io.*;
  import java.lang.*;
  import java.util.*;
  import javax.swing.*;

public class Compilador implements CompiladorConstants {
  public static  FileOutputStream Token1;
  public static  DataOutputStream Token2;


        public static void main(String args[]) throws ParseException
        {
                Actualizador modelo= new Actualizador();
        Vista vista=new Vista();

        OyenteBox oye= new OyenteBox(vista, modelo);
        OyenteBotones oye2= new OyenteBotones(vista, modelo);
        vista.addEventoCounter(oye);
        vista.addEventoBotones(oye2);
        }





  public void analisisLexico(Vista v, Compilador comp)  throws ParseException
  {
                                //Análisis Léxico	
                                v.output.appendBlue("*****INICIANDO AN\u00c1LISIS L\u00c9XICO*****\u005cn\u005ct");
                                try
                                        {comp.input(comp, v);}
                                        catch(ParseException e)
                                        {
                                         v.output.appendRed("Error sint\u00e1ctico: "+e.getMessage());

                                        }
                                        catch(TokenMgrError e)
                                        {
                                          v.output.appendRed("Error: Caracter no v\u00e1lido: "+e.getMessage());

                                        }
        }

        public void analisisSintactico(Vista v, Compilador comp)throws ParseException
        {
        //Análisis Síntáctico	
                                v.output2.appendBlue("\u005cn\u005ct*****INICIANDO AN\u00c1LISIS SINT\u00c1CTICO*****\u005cn\u005ct");
                                v.numErr=0;
                                v.errores="";

                                try
                                        {
                                        v.errores="";
                                        comp.programa(v);

                                        if(v.numErr==0)
                                        {
                                        v.output2.appendGreen("\u005cn\u005crCompilaci\u00f3n Terminada con \u00c9xito");
                                        JOptionPane.showMessageDialog(v, "Compilaci\u00f3n exitosa", "No encontramos ning\u00fan problema" , JOptionPane.INFORMATION_MESSAGE);
                                        }
                                        else
                                        {
                                        v.output2.appendRed("\u005cn\u005crCompilaci\u00c3\u00b3n Terminada con"+v.numErr+" errores:\u005cn\u005cr");
                                        v.output2.appendRed(v.errores);
                                        }


                                        System.out.println("ANALISIS SINTACTICO FINALIZADO");
                                        }
                                        catch(ParseException e)
                                        {
                                         v.output2.append("Error sint\u00e1ctico: "+e.getMessage());
                                        }
                                        catch(TokenMgrError e)
                                        {
                                          v.output2.append("Error: Caracter no v\u00e1lido: "+e.getMessage());
                                        }
        }


  public static void cerrar()
  {
    try
    {
      Token1.close();
    }
    catch (IOException Ex)
    {
      System.out.println("No se cerro el archivo corectamente");
    }
   }

  final public void input(Compilador analiza, Vista v) throws ParseException {String mensaje;
    label_1:
    while (true) {
      mensaje = revisarTokens();
//analiza.archtoken_escribe(mensaje);
       v.output.append(mensaje+"\u005cn");
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case si:
      case sino:
      case elegir:
      case caso:
      case salir:
      case falta:
      case in:
      case ent:
      case flot:
      case cad:
      case bool:
      case mode:
      case ls:
      case history:
      case ayuda:
      case help:
      case print:
      case rm:
      case function:
      case mientras:
      case hasta:
      case hacer:
      case enojo:
      case palito:
      case grados:
      case admira1:
      case admira2:
      case pesos:
      case porciento:
      case amperson:
      case comilla1:
      case abrepregunta:
      case comilla2:
      case comilla3:
      case dospuntosarriba:
      case culebrita:
      case guionbajo:
      case abreparentesis:
      case cierraparentesis:
      case abrellave:
      case cierrallave:
      case abrecorchete:
      case cierracorchete:
      case comillas:
      case gatito:
      case puntocoma:
      case punto:
      case coma:
      case dospuntos:
      case suma:
      case resta:
      case multiplicar:
      case dividir:
      case modulo:
      case modulodos:
      case potencia:
      case y:
      case o:
      case menor:
      case mayor:
      case menorigual:
      case mayorigual:
      case igual:
      case diferente:
      case asignacion:
      case asignaciondos:
      case aumento:
      case decremento:
      case num:
      case flotante:
      case booleano:
      case nulo:
      case cadena:
      case comentario:
      case ident:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(0);
  }

  final public String revisarTokens() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case si:{
      //CONDICIONALES
      
      t = jj_consume_token(si);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada if" );}
      break;
      }
    case sino:{
      t = jj_consume_token(sino);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada else");}
      break;
      }
    case elegir:{
      t = jj_consume_token(elegir);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada switch");}
      break;
      }
    case caso:{
      t = jj_consume_token(caso);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada case");}
      break;
      }
    case salir:{
      t = jj_consume_token(salir);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada break");}
      break;
      }
    case falta:{
      t = jj_consume_token(falta);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada default");}
      break;
      }
    case in:{
      t = jj_consume_token(in);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada in");}
      break;
      }
    case ent:{
      t = jj_consume_token(ent);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada int");}
      break;
      }
    case flot:{
      t = jj_consume_token(flot);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada float");}
      break;
      }
    case cad:{
      t = jj_consume_token(cad);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct Palabra reservada string");}
      break;
      }
    case bool:{
      t = jj_consume_token(bool);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada booleano");}
      break;
      }
    case mode:{
      t = jj_consume_token(mode);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada mode");}
      break;
      }
    case ls:{
      t = jj_consume_token(ls);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada ls");}
      break;
      }
    case history:{
      t = jj_consume_token(history);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada history");}
      break;
      }
    case ayuda:{
      t = jj_consume_token(ayuda);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada ?");}
      break;
      }
    case help:{
      t = jj_consume_token(help);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada help");}
      break;
      }
    case print:{
      t = jj_consume_token(print);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada print");}
      break;
      }
    case rm:{
      t = jj_consume_token(rm);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada rm");}
      break;
      }
    case function:{
      t = jj_consume_token(function);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada function");}
      break;
      }
    case mientras:{
      t = jj_consume_token(mientras);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada while");}
      break;
      }
    case hasta:{
      t = jj_consume_token(hasta);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada for");}
      break;
      }
    case hacer:{
      t = jj_consume_token(hacer);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada hacer");}
      break;
      }
    case abreparentesis:{
      t = jj_consume_token(abreparentesis);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador (");}
      break;
      }
    case cierraparentesis:{
      t = jj_consume_token(cierraparentesis);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador )");}
      break;
      }
    case abrellave:{
      t = jj_consume_token(abrellave);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador {");}
      break;
      }
    case cierrallave:{
      t = jj_consume_token(cierrallave);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador }");}
      break;
      }
    case abrecorchete:{
      t = jj_consume_token(abrecorchete);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador [");}
      break;
      }
    case cierracorchete:{
      t = jj_consume_token(cierracorchete);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador ]");}
      break;
      }
    case comillas:{
      t = jj_consume_token(comillas);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador \u005c" ");}
      break;
      }
    case gatito:{
      t = jj_consume_token(gatito);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador #");}
      break;
      }
    case puntocoma:{
      t = jj_consume_token(puntocoma);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador ;");}
      break;
      }
    case punto:{
      t = jj_consume_token(punto);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador .");}
      break;
      }
    case coma:{
      t = jj_consume_token(coma);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador ,");}
      break;
      }
    case dospuntos:{
      t = jj_consume_token(dospuntos);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Delimitador :");}
      break;
      }
    case enojo:{
      t = jj_consume_token(enojo);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido \u00ac");}
      break;
      }
    case palito:{
      t = jj_consume_token(palito);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido |");}
      break;
      }
    case grados:{
      t = jj_consume_token(grados);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido \u00b0");}
      break;
      }
    case admira1:{
      t = jj_consume_token(admira1);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido !");}
      break;
      }
    case admira2:{
      t = jj_consume_token(admira2);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido \u00a1");}
      break;
      }
    case pesos:{
      t = jj_consume_token(pesos);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido $");}
      break;
      }
    case porciento:{
      t = jj_consume_token(porciento);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido %");}
      break;
      }
    case amperson:{
      t = jj_consume_token(amperson);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido &");}
      break;
      }
    case comilla1:{
      t = jj_consume_token(comilla1);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido '");}
      break;
      }
    case abrepregunta:{
      t = jj_consume_token(abrepregunta);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido \u00bf");}
      break;
      }
    case comilla2:{
      t = jj_consume_token(comilla2);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido \u00b4");}
      break;
      }
    case comilla3:{
      t = jj_consume_token(comilla3);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido `");}
      break;
      }
    case dospuntosarriba:{
      t = jj_consume_token(dospuntosarriba);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido \u00a8");}
      break;
      }
    case culebrita:{
      t = jj_consume_token(culebrita);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido ~");}
      break;
      }
    case guionbajo:{
      t = jj_consume_token(guionbajo);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Caracter no valido _");}
      break;
      }
    case suma:{
      t = jj_consume_token(suma);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico SUMA +");}
      break;
      }
    case resta:{
      t = jj_consume_token(resta);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico RESTA -");}
      break;
      }
    case multiplicar:{
      t = jj_consume_token(multiplicar);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico PRODUCTO *");}
      break;
      }
    case dividir:{
      t = jj_consume_token(dividir);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico COCIENTE /");}
      break;
      }
    case modulo:{
      t = jj_consume_token(modulo);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico RESIDUO %%");}
      break;
      }
    case modulodos:{
      t = jj_consume_token(modulodos);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico RESIDUO %/%");}
      break;
      }
    case potencia:{
      t = jj_consume_token(potencia);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico POTENCIA ^");}
      break;
      }
    case y:{
      t = jj_consume_token(y);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador logico AND &");}
      break;
      }
    case o:{
      t = jj_consume_token(o);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador logico OR ||");}
      break;
      }
    case menor:{
      t = jj_consume_token(menor);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador comparativo <");}
      break;
      }
    case mayor:{
      t = jj_consume_token(mayor);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador comparativo >");}
      break;
      }
    case menorigual:{
      t = jj_consume_token(menorigual);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador comparativo <=");}
      break;
      }
    case mayorigual:{
      t = jj_consume_token(mayorigual);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador comparativo >=");}
      break;
      }
    case asignacion:{
      t = jj_consume_token(asignacion);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico =");}
      break;
      }
    case asignaciondos:{
      t = jj_consume_token(asignaciondos);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico <-");}
      break;
      }
    case igual:{
      t = jj_consume_token(igual);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador comparativo ==");}
      break;
      }
    case diferente:{
      t = jj_consume_token(diferente);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador comparativo !=");}
      break;
      }
    case aumento:{
      t = jj_consume_token(aumento);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico AUMENTO ++");}
      break;
      }
    case decremento:{
      t = jj_consume_token(decremento);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Operador aritmetico DECREMENTO --");}
      break;
      }
    case nulo:{
      t = jj_consume_token(nulo);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Palabra reservada Valor nulo");}
      break;
      }
    case num:{
      t = jj_consume_token(num);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Tipo de Dato ENTERO");}
      break;
      }
    case flotante:{
      t = jj_consume_token(flotante);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Tipo de Dato FLOTANTE");}
      break;
      }
    case booleano:{
      t = jj_consume_token(booleano);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Tipo de Dato BOOLEANO");}
      break;
      }
    case cadena:{
      t = jj_consume_token(cadena);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Tipo de Dato CADENA");}
      break;
      }
    case comentario:{
      t = jj_consume_token(comentario);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Comentario");}
      break;
      }
    case ident:{
      t = jj_consume_token(ident);
{if ("" != null) return ( t.image +"\u005ct\u005ct\u005ct\u005ct Identificador");}
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

///////////////////////////////////////////////////////////////////////////////
///A	N	A	L	I	S	I	S		S	I	N	T	A	C	T	I	C	O
///////////////////////////////////////////////////////////////////////////////
  final public 
void programa(Vista v) throws ParseException {
    try {
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case comentario:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
        jj_consume_token(comentario);
      }
      instrucciones(v);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case comentario:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        jj_consume_token(comentario);
      }
      jj_consume_token(0);
    } catch (ParseException e) {
v.numErr++;
                v.errores=v.errores+"\u005cnError sint\u00e1ctico: Error al crear estructura el fichero\u005cn\u005cr"+e.getMessage();
                Token t;
                do
                {
                t=getNextToken();
                }while(
                //t.kind !=fin  && 
                t.kind != EOF);
    }
  }

  final public void instrucciones(Vista v) throws ParseException {
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case si:
      case elegir:
      case mode:
      case ls:
      case history:
      case ayuda:
      case help:
      case print:
      case rm:
      case function:
      case mientras:
      case hasta:
      case hacer:
      case comentario:
      case ident:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ident:{
        declaraciones(v);
        break;
        }
      case mientras:
      case hasta:
      case hacer:{
        ciclos(v);
        break;
        }
      case si:
      case elegir:{
        condicionales(v);
        break;
        }
      case mode:
      case ls:
      case history:
      case ayuda:
      case help:
      case print:
      case rm:
      case function:{
        es(v);
        break;
        }
      case comentario:{
        comentarios();
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

//Arreglos
  final public void arreglo() throws ParseException {
    jj_consume_token(abrecorchete);
    dato();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case coma:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      jj_consume_token(coma);
      dato();
    }
    jj_consume_token(cierracorchete);
  }

//DECLARACIONES
  final public 
void declaraciones(Vista v) throws ParseException {System.out.println("Declaro");
    try {
      jj_consume_token(ident);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case asignacion:
      case asignaciondos:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case asignacion:{
          jj_consume_token(asignacion);
          break;
          }
        case asignaciondos:{
          jj_consume_token(asignaciondos);
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case abreparentesis:
        case resta:
        case num:
        case flotante:
        case booleano:
        case nulo:
        case cadena:
        case ident:{
          operacion(v);
          break;
          }
        case abrecorchete:{
          arreglo();
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        ;
      }
      jj_consume_token(puntocoma);
    } catch (ParseException e) {
v.numErr++;
                v.errores=v.errores+"Error sint\u00e1ctico: Error al declarar variable\u005cn\u005cr"+e.getMessage();
                Token t;

                do
                {t=getNextToken();
                }while(t.kind != EOF  && t.kind!=puntocoma &&t.kind!=asignaciondos &&t.kind!=asignacion  );
    }
  }

/*void declara():
{}
{
<ent>
|<flot>
//|<car>
|<cad>
|<bool>
}*/
  final public 

void dato() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case num:{
      jj_consume_token(num);
      break;
      }
    case flotante:{
      jj_consume_token(flotante);
      break;
      }
    case booleano:{
      jj_consume_token(booleano);
      break;
      }
    case nulo:{
      jj_consume_token(nulo);
      break;
      }
    case cadena:{
      jj_consume_token(cadena);
      break;
      }
    case resta:{
      neg();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void neg() throws ParseException {
    jj_consume_token(resta);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case num:{
      jj_consume_token(num);
      break;
      }
    case flotante:{
      jj_consume_token(flotante);
      break;
      }
    case ident:{
      jj_consume_token(ident);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void operacion(Vista v) throws ParseException {System.out.println("Operacion realizada");
    operando(v);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case suma:
      case resta:
      case multiplicar:
      case dividir:
      case modulo:
      case modulodos:
      case potencia:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_6;
      }
      operador();
      operando(v);
    }
  }

  final public void operador() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case suma:{
      jj_consume_token(suma);
      break;
      }
    case resta:{
      jj_consume_token(resta);
      break;
      }
    case multiplicar:{
      jj_consume_token(multiplicar);
      break;
      }
    case dividir:{
      jj_consume_token(dividir);
      break;
      }
    case modulo:{
      jj_consume_token(modulo);
      break;
      }
    case modulodos:{
      jj_consume_token(modulodos);
      break;
      }
    case potencia:{
      jj_consume_token(potencia);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void operando(Vista v) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case resta:
    case num:
    case flotante:
    case booleano:
    case nulo:
    case cadena:
    case ident:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ident:{
        jj_consume_token(ident);
        break;
        }
      case resta:
      case num:
      case flotante:
      case booleano:
      case nulo:
      case cadena:{
        dato();
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    case abreparentesis:{
      jj_consume_token(abreparentesis);
      operacion(v);
      jj_consume_token(cierraparentesis);
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void asignaciones(Vista v) throws ParseException {
    try {
      jj_consume_token(ident);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case asignacion:
      case asignaciondos:
      case aumento:
      case decremento:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case aumento:
        case decremento:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case aumento:{
            jj_consume_token(aumento);
            break;
            }
          case decremento:{
            jj_consume_token(decremento);
            break;
            }
          default:
            jj_la1[16] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
          }
        case asignacion:
        case asignaciondos:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case asignacion:{
            jj_consume_token(asignacion);
            break;
            }
          case asignaciondos:{
            jj_consume_token(asignaciondos);
            break;
            }
          default:
            jj_la1[17] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          operacion(v);
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      jj_consume_token(puntocoma);
    } catch (ParseException e) {
v.numErr++;
                v.errores=v.errores+"Error sint\u00e1ctico: Error en asignaci\u00f3n\u005cn\u005cr"+e.getMessage();
                Token t;

                do
                {t=getNextToken();
                }while(t.kind != EOF  && t.kind!=puntocoma  && t.kind!=asignacion && t.kind!=asignaciondos   &&  t.kind!=aumento  &&t.kind!=decremento );
    }
  }

  final public void comentarios() throws ParseException {
    jj_consume_token(comentario);
  }

  final public void es(Vista v) throws ParseException {
    printwrite(v);
  }

  final public void printwrite(Vista v) throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case mode:{
        jj_consume_token(mode);
        jj_consume_token(abreparentesis);
        jj_consume_token(ident);
        jj_consume_token(cierraparentesis);
        jj_consume_token(puntocoma);
        break;
        }
      case ls:{
        jj_consume_token(ls);
        jj_consume_token(abreparentesis);
        jj_consume_token(cierraparentesis);
        jj_consume_token(puntocoma);
        break;
        }
      case history:{
        jj_consume_token(history);
        jj_consume_token(abreparentesis);
        jj_consume_token(cierraparentesis);
        jj_consume_token(puntocoma);
        break;
        }
      case ayuda:{
        jj_consume_token(ayuda);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case mode:{
          jj_consume_token(mode);
          break;
          }
        case ls:{
          jj_consume_token(ls);
          break;
          }
        case history:{
          jj_consume_token(history);
          break;
          }
        case help:{
          jj_consume_token(help);
          break;
          }
        case print:{
          jj_consume_token(print);
          break;
          }
        case rm:{
          jj_consume_token(rm);
          break;
          }
        case function:{
          jj_consume_token(function);
          break;
          }
        case si:{
          jj_consume_token(si);
          break;
          }
        case sino:{
          jj_consume_token(sino);
          break;
          }
        case elegir:{
          jj_consume_token(elegir);
          break;
          }
        case caso:{
          jj_consume_token(caso);
          break;
          }
        case salir:{
          jj_consume_token(salir);
          break;
          }
        case falta:{
          jj_consume_token(falta);
          break;
          }
        case in:{
          jj_consume_token(in);
          break;
          }
        case mientras:{
          jj_consume_token(mientras);
          break;
          }
        case hasta:{
          jj_consume_token(hasta);
          break;
          }
        case suma:{
          jj_consume_token(suma);
          break;
          }
        case resta:{
          jj_consume_token(resta);
          break;
          }
        case multiplicar:{
          jj_consume_token(multiplicar);
          break;
          }
        case dividir:{
          jj_consume_token(dividir);
          break;
          }
        case modulo:{
          jj_consume_token(modulo);
          break;
          }
        case modulodos:{
          jj_consume_token(modulodos);
          break;
          }
        case potencia:{
          jj_consume_token(potencia);
          break;
          }
        case y:{
          jj_consume_token(y);
          break;
          }
        case o:{
          jj_consume_token(o);
          break;
          }
        case menor:{
          jj_consume_token(menor);
          break;
          }
        case mayor:{
          jj_consume_token(mayor);
          break;
          }
        case menorigual:{
          jj_consume_token(menorigual);
          break;
          }
        case mayorigual:{
          jj_consume_token(mayorigual);
          break;
          }
        case igual:{
          jj_consume_token(igual);
          break;
          }
        case diferente:{
          jj_consume_token(diferente);
          break;
          }
        case asignacion:{
          jj_consume_token(asignacion);
          break;
          }
        case asignaciondos:{
          jj_consume_token(asignaciondos);
          break;
          }
        case aumento:{
          jj_consume_token(aumento);
          break;
          }
        case decremento:{
          jj_consume_token(decremento);
          break;
          }
        case gatito:{
          jj_consume_token(gatito);
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(puntocoma);
        break;
        }
      case help:{
        jj_consume_token(help);
        jj_consume_token(abreparentesis);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case mode:{
          jj_consume_token(mode);
          break;
          }
        case ls:{
          jj_consume_token(ls);
          break;
          }
        case history:{
          jj_consume_token(history);
          break;
          }
        case help:{
          jj_consume_token(help);
          break;
          }
        case print:{
          jj_consume_token(print);
          break;
          }
        case rm:{
          jj_consume_token(rm);
          break;
          }
        case function:{
          jj_consume_token(function);
          break;
          }
        case si:{
          jj_consume_token(si);
          break;
          }
        case sino:{
          jj_consume_token(sino);
          break;
          }
        case elegir:{
          jj_consume_token(elegir);
          break;
          }
        case caso:{
          jj_consume_token(caso);
          break;
          }
        case salir:{
          jj_consume_token(salir);
          break;
          }
        case falta:{
          jj_consume_token(falta);
          break;
          }
        case in:{
          jj_consume_token(in);
          break;
          }
        case mientras:{
          jj_consume_token(mientras);
          break;
          }
        case hasta:{
          jj_consume_token(hasta);
          break;
          }
        case suma:{
          jj_consume_token(suma);
          break;
          }
        case resta:{
          jj_consume_token(resta);
          break;
          }
        case multiplicar:{
          jj_consume_token(multiplicar);
          break;
          }
        case dividir:{
          jj_consume_token(dividir);
          break;
          }
        case modulo:{
          jj_consume_token(modulo);
          break;
          }
        case modulodos:{
          jj_consume_token(modulodos);
          break;
          }
        case potencia:{
          jj_consume_token(potencia);
          break;
          }
        case y:{
          jj_consume_token(y);
          break;
          }
        case o:{
          jj_consume_token(o);
          break;
          }
        case menor:{
          jj_consume_token(menor);
          break;
          }
        case mayor:{
          jj_consume_token(mayor);
          break;
          }
        case menorigual:{
          jj_consume_token(menorigual);
          break;
          }
        case mayorigual:{
          jj_consume_token(mayorigual);
          break;
          }
        case igual:{
          jj_consume_token(igual);
          break;
          }
        case diferente:{
          jj_consume_token(diferente);
          break;
          }
        case asignacion:{
          jj_consume_token(asignacion);
          break;
          }
        case asignaciondos:{
          jj_consume_token(asignaciondos);
          break;
          }
        case aumento:{
          jj_consume_token(aumento);
          break;
          }
        case decremento:{
          jj_consume_token(decremento);
          break;
          }
        case gatito:{
          jj_consume_token(gatito);
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(cierraparentesis);
        jj_consume_token(puntocoma);
        break;
        }
      case print:{
        jj_consume_token(print);
        jj_consume_token(abreparentesis);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case cadena:{
          jj_consume_token(cadena);
          break;
          }
        case abreparentesis:
        case resta:
        case num:
        case flotante:
        case booleano:
        case nulo:
        case ident:{
          operacion(v);
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(cierraparentesis);
        jj_consume_token(puntocoma);
        break;
        }
      case rm:{
        jj_consume_token(rm);
        jj_consume_token(abreparentesis);
        jj_consume_token(ident);
        jj_consume_token(cierraparentesis);
        jj_consume_token(puntocoma);
        break;
        }
      case function:{
        jj_consume_token(function);
        jj_consume_token(ident);
        jj_consume_token(abreparentesis);
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case ident:{
            ;
            break;
            }
          default:
            jj_la1[23] = jj_gen;
            break label_7;
          }
          jj_consume_token(ident);
          label_8:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case coma:{
              ;
              break;
              }
            default:
              jj_la1[24] = jj_gen;
              break label_8;
            }
            jj_consume_token(coma);
            jj_consume_token(ident);
          }
        }
        jj_consume_token(cierraparentesis);
        jj_consume_token(abrellave);
        instrucciones(v);
        jj_consume_token(cierrallave);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
v.numErr++;
                v.errores=v.errores+"Error sint\u00e1ctico: Error en instrucci\u00f3n de salida\u005cn\u005cr" +e.getMessage();
                Token t;

                do
                {t=getNextToken();
                }while(t.kind != EOF && t.kind!=puntocoma);
    }
  }

/*void palabra():
{}
{
		(<mode>|<ls>|<history>|<help>|<print>|<rm>|<function>
		|<si>|<sino>|<elegir>|<caso>|<salir>|<falta>|<in>|<mientras>|<hasta>|<suma>|<resta>
		|<multiplicar>|<dividir>|<modulo>|<modulodos>|<potencia>|<y>|<o>|<menor>|<mayor>
		|<menorigual>|<mayorigual>|<igual>|<diferente>|<asignacion>|<asignaciondos>
		|<aumento>|<decremento>|<gatito>)
}*/
  final public 
void concatenar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case resta:
    case num:
    case flotante:
    case booleano:
    case nulo:
    case cadena:{
      dato();
      break;
      }
    case ident:{
      jj_consume_token(ident);
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case suma:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_9;
      }
      jj_consume_token(suma);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case resta:
      case num:
      case flotante:
      case booleano:
      case nulo:
      case cadena:{
        dato();
        break;
        }
      case ident:{
        jj_consume_token(ident);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

/*void scan(Vista v):
{}
{

                try{
		<leer><abreparentesis> tipodato() <coma> <ident> <cierraparentesis><puntocoma>
		}
		catch(ParseException e)
		{
		v.numErr++;
		v.errores=v.errores+"Error sint�ctico: Error en instrucci�n de entrada\n\r" +e.getMessage();
		Token t;	
		
		do
		{t=getNextToken();	
		}while(t.kind != EOF  && t.kind!=puntocoma && t.kind!=cierraparentesis  && t.kind!=ident && t.kind!=coma && t.kind!=abreparentesis);
		}
}*/

/*void tipodato():
{}
{
<ent>
|<flot>
|<car>
|<cad>
|<bool>
}*/
  final public 
void condicionales(Vista v) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case si:{
      ifelse(v);
      break;
      }
    case elegir:{
      switchh(v);
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ifelse(Vista v) throws ParseException {
    try {
      jj_consume_token(si);
      jj_consume_token(abreparentesis);
      condicion(v);
      jj_consume_token(cierraparentesis);
      jj_consume_token(abrellave);
      instrucciones(v);
      jj_consume_token(cierrallave);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case sino:{
        jj_consume_token(sino);
        jj_consume_token(abrellave);
        instrucciones(v);
        jj_consume_token(cierrallave);
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        ;
      }
    } catch (ParseException e) {
v.numErr++;
                v.errores=v.errores+"Error sint\u00e1ctico: Error en condicional if-else\u005cn\u005cr" +e.getMessage();
                Token t;

                do
                {t=getNextToken();

            }while(t.kind != EOF && t.kind!=cierrallave && t.kind!=abrellave && t.kind!=sino && t.kind!=cierrallave && t.kind!=abrellave && t.kind!=cierraparentesis && t.kind!=abreparentesis );
    }
  }

  final public void casos(Vista v) throws ParseException {
    label_10:
    while (true) {
      jj_consume_token(caso);
      dato();
      jj_consume_token(dospuntos);
      instrucciones(v);
      breakk();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case caso:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_10;
      }
    }
    defaultt(v);
  }

  final public void breakk() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case salir:{
      jj_consume_token(salir);
      jj_consume_token(puntocoma);
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      ;
    }
  }

  final public void defaultt(Vista v) throws ParseException {
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case falta:{
        ;
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        break label_11;
      }
      jj_consume_token(falta);
      jj_consume_token(dospuntos);
      instrucciones(v);
      breakk();
    }
  }

  final public void switchh(Vista v) throws ParseException {
    try {
      jj_consume_token(elegir);
      jj_consume_token(abreparentesis);
      jj_consume_token(ident);
      jj_consume_token(cierraparentesis);
      jj_consume_token(abrellave);
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case caso:{
          ;
          break;
          }
        default:
          jj_la1[34] = jj_gen;
          break label_12;
        }
        casos(v);
      }
      jj_consume_token(cierrallave);
    } catch (ParseException e) {
v.numErr++;
                v.errores=v.errores+"Error sint\u00e1ctico: Error en condicional m\u00faltiple \u005cn\u005cr" +e.getMessage();
                Token t;

                do
                {t=getNextToken();

            }while(t.kind != EOF && t.kind!=cierrallave && t.kind!=abrellave && t.kind!=cierraparentesis && t.kind!=ident && t.kind!=abreparentesis);
    }
  }

//CONDICIONALES	
  final public 
void condicion(Vista v) throws ParseException {
    condicional(v);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case y:
      case o:{
        ;
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        break label_13;
      }
      operadorlogico();
      condicional(v);
    }
  }

  final public void operadorlogico() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case o:{
      jj_consume_token(o);
      break;
      }
    case y:{
      jj_consume_token(y);
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void condicional(Vista v) throws ParseException {
    comparacion(v);
  }

  final public void comparacion(Vista v) throws ParseException {
    operacion(v);
    comparador();
    operacion(v);
  }

  final public void comparador() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case menor:{
      jj_consume_token(menor);
      break;
      }
    case mayor:{
      jj_consume_token(mayor);
      break;
      }
    case menorigual:{
      jj_consume_token(menorigual);
      break;
      }
    case mayorigual:{
      jj_consume_token(mayorigual);
      break;
      }
    case igual:{
      jj_consume_token(igual);
      break;
      }
    case diferente:{
      jj_consume_token(diferente);
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//CICLOS
  final public void ciclos(Vista v) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case mientras:{
      wwhile(v);
      break;
      }
    case hacer:{
      dowhile(v);
      break;
      }
    case hasta:{
      ffor(v);
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void wwhile(Vista v) throws ParseException {
    try {
      jj_consume_token(mientras);
      jj_consume_token(abreparentesis);
      condicion(v);
      jj_consume_token(cierraparentesis);
      jj_consume_token(abrellave);
      instrucciones(v);
      jj_consume_token(cierrallave);
    } catch (ParseException e) {
v.numErr++;
                v.errores=v.errores+"Error sint\u00e1ctico: Error en ciclo while \u005cn\u005cr" +e.getMessage();
                Token t;

                do
                {t=getNextToken();

                }while(t.kind != EOF && t.kind!=cierrallave && t.kind!=abrellave && t.kind!=cierraparentesis && t.kind!=abreparentesis);
    }
  }

  final public void dowhile(Vista v) throws ParseException {
    jj_consume_token(hacer);
    jj_consume_token(abrellave);
    instrucciones(v);
    jj_consume_token(cierrallave);
    jj_consume_token(mientras);
    jj_consume_token(abreparentesis);
    condicion(v);
    jj_consume_token(cierraparentesis);
    jj_consume_token(puntocoma);
  }

  final public void ffor(Vista v) throws ParseException {
    try {
      jj_consume_token(hasta);
      jj_consume_token(abreparentesis);
      jj_consume_token(ident);
      jj_consume_token(in);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case num:{
        jj_consume_token(num);
        break;
        }
      case ident:{
        jj_consume_token(ident);
        break;
        }
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(dospuntos);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case num:{
        jj_consume_token(num);
        break;
        }
      case ident:{
        jj_consume_token(ident);
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(cierraparentesis);
      jj_consume_token(abrellave);
      instrucciones(v);
      jj_consume_token(cierrallave);
    } catch (ParseException e) {
v.numErr++;
                v.errores=v.errores+"Error sint\u00e1ctico: Error en ciclo for \u005cn\u005cr" +e.getMessage();
                Token t;

                do
                {t=getNextToken();

                }while(t.kind != EOF && t.kind!=cierrallave && t.kind!=abrellave && t.kind!=cierraparentesis && t.kind!=ident
                                && t.kind!=num && t.kind!=dospuntos && t.kind!=ident && t.kind!=num && t.kind!=in && t.kind!=ident && t.kind!=abreparentesis);
    }
  }

  /** Generated Token Manager. */
  public CompiladorTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[41];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffffffe0,0xffffffe0,0x0,0x0,0x7ff00a0,0x7ff00a0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3f70fe0,0x3f70fe0,0x0,0x0,0x0,0xff0000,0x0,0x0,0x0,0xa0,0x40,0x100,0x200,0x400,0x100,0x0,0x0,0x0,0x7000000,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xffffffff,0xffffffff,0x0,0x0,0x0,0x0,0x100000,0x0,0x804400,0x0,0x800000,0x0,0x1fc00000,0x1fc00000,0x800000,0x800400,0x0,0x0,0x0,0x0,0xffc20000,0xffc20000,0x800400,0x0,0x100000,0x0,0x800000,0x400000,0x800000,0x0,0x0,0x0,0x0,0x0,0x0,0x60000000,0x60000000,0x80000000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x71fff,0x71fff,0x20000,0x20000,0x60000,0x60000,0x0,0x60,0x51e00,0x60,0x11e00,0x40600,0x0,0x0,0x51e00,0x51e00,0x180,0x60,0x1e0,0x1e0,0x1ff,0x1ff,0x51e00,0x40000,0x0,0x0,0x51e00,0x0,0x51e00,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1f,0x0,0x40200,0x40200,};
   }

  /** Constructor with InputStream. */
  public Compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compilador(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compilador(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compilador(CompiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[83];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 41; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 83; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
