/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int si = 5;
  /** RegularExpression Id. */
  int sino = 6;
  /** RegularExpression Id. */
  int elegir = 7;
  /** RegularExpression Id. */
  int caso = 8;
  /** RegularExpression Id. */
  int salir = 9;
  /** RegularExpression Id. */
  int falta = 10;
  /** RegularExpression Id. */
  int ent = 11;
  /** RegularExpression Id. */
  int largo = 12;
  /** RegularExpression Id. */
  int flot = 13;
  /** RegularExpression Id. */
  int doble = 14;
  /** RegularExpression Id. */
  int cad = 15;
  /** RegularExpression Id. */
  int bool = 16;
  /** RegularExpression Id. */
  int print = 17;
  /** RegularExpression Id. */
  int leer = 18;
  /** RegularExpression Id. */
  int function = 19;
  /** RegularExpression Id. */
  int mientras = 20;
  /** RegularExpression Id. */
  int hasta = 21;
  /** RegularExpression Id. */
  int hacer = 22;
  /** RegularExpression Id. */
  int inicio = 23;
  /** RegularExpression Id. */
  int fin = 24;
  /** RegularExpression Id. */
  int enojo = 25;
  /** RegularExpression Id. */
  int palito = 26;
  /** RegularExpression Id. */
  int grados = 27;
  /** RegularExpression Id. */
  int admira1 = 28;
  /** RegularExpression Id. */
  int admira2 = 29;
  /** RegularExpression Id. */
  int pesos = 30;
  /** RegularExpression Id. */
  int amperson = 31;
  /** RegularExpression Id. */
  int comilla1 = 32;
  /** RegularExpression Id. */
  int abrepregunta = 33;
  /** RegularExpression Id. */
  int comilla2 = 34;
  /** RegularExpression Id. */
  int comilla3 = 35;
  /** RegularExpression Id. */
  int dospuntosarriba = 36;
  /** RegularExpression Id. */
  int culebrita = 37;
  /** RegularExpression Id. */
  int guionbajo = 38;
  /** RegularExpression Id. */
  int gato = 39;
  /** RegularExpression Id. */
  int abreparentesis = 40;
  /** RegularExpression Id. */
  int cierraparentesis = 41;
  /** RegularExpression Id. */
  int abrellave = 42;
  /** RegularExpression Id. */
  int cierrallave = 43;
  /** RegularExpression Id. */
  int abrecorchete = 44;
  /** RegularExpression Id. */
  int cierracorchete = 45;
  /** RegularExpression Id. */
  int comillas = 46;
  /** RegularExpression Id. */
  int gatito = 47;
  /** RegularExpression Id. */
  int puntocoma = 48;
  /** RegularExpression Id. */
  int punto = 49;
  /** RegularExpression Id. */
  int coma = 50;
  /** RegularExpression Id. */
  int dospuntos = 51;
  /** RegularExpression Id. */
  int suma = 52;
  /** RegularExpression Id. */
  int resta = 53;
  /** RegularExpression Id. */
  int multiplicar = 54;
  /** RegularExpression Id. */
  int dividir = 55;
  /** RegularExpression Id. */
  int modulo = 56;
  /** RegularExpression Id. */
  int potencia = 57;
  /** RegularExpression Id. */
  int y = 58;
  /** RegularExpression Id. */
  int o = 59;
  /** RegularExpression Id. */
  int menor = 60;
  /** RegularExpression Id. */
  int mayor = 61;
  /** RegularExpression Id. */
  int menorigual = 62;
  /** RegularExpression Id. */
  int mayorigual = 63;
  /** RegularExpression Id. */
  int igual = 64;
  /** RegularExpression Id. */
  int diferente = 65;
  /** RegularExpression Id. */
  int asignacion = 66;
  /** RegularExpression Id. */
  int aumento = 67;
  /** RegularExpression Id. */
  int decremento = 68;
  /** RegularExpression Id. */
  int num = 69;
  /** RegularExpression Id. */
  int flotante = 70;
  /** RegularExpression Id. */
  int booleano = 71;
  /** RegularExpression Id. */
  int nulo = 72;
  /** RegularExpression Id. */
  int unicodeMin = 73;
  /** RegularExpression Id. */
  int unicodeMay = 74;
  /** RegularExpression Id. */
  int unicodeSimb = 75;
  /** RegularExpression Id. */
  int cadena = 76;
  /** RegularExpression Id. */
  int comentario = 77;
  /** RegularExpression Id. */
  int ident = 78;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
    "\"\\n\"",
    "<si>",
    "<sino>",
    "<elegir>",
    "<caso>",
    "<salir>",
    "<falta>",
    "<ent>",
    "<largo>",
    "<flot>",
    "<doble>",
    "<cad>",
    "<bool>",
    "<print>",
    "<leer>",
    "<function>",
    "<mientras>",
    "<hasta>",
    "<hacer>",
    "<inicio>",
    "<fin>",
    "\"\\u00ac\"",
    "\"|\"",
    "\"\\u00b0\"",
    "\"!\"",
    "\"\\u00a1\"",
    "\"$\"",
    "\"&\"",
    "\"\\\'\"",
    "\"\\u00bf\"",
    "\"\\u00b4\"",
    "\"`\"",
    "\"\\u00a8\"",
    "\"~\"",
    "\"_\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "\"//\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "<num>",
    "<flotante>",
    "<booleano>",
    "\"null\"",
    "<unicodeMin>",
    "<unicodeMay>",
    "<unicodeSimb>",
    "<cadena>",
    "<comentario>",
    "<ident>",
  };

}
